#spring configuration
server:
  error:
    include-stacktrace: never

spring:
  #h2 database configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    initialization-mode: always
    data: classpath:fakeData.sql
  #Spring DataSource configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
logging:
  level:
    jp.co.axa.apidemo: DEBUG