INSERT INTO USERINFO (ID,USERNAME, PASSWORD, ROLE) VALUES (null,'admin','admin123','ADMIN,EDITOR,VIEWER,');
INSERT INTO USERINFO (ID,USERNAME, PASSWORD, ROLE) VALUES (null,'editor','editor123','EDITOR');
INSERT INTO USERINFO (ID,USERNAME, PASSWORD, ROLE) VALUES (null,'viewer','viewer123','VIEWER');

INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT) VALUES (1,'Emp1','959500','TECH1');
INSERT INTO EMPLOYEE (ID, EMPLOYEE_NAME, EMPLOYEE_SALARY, DEPARTMENT) VALUES (2,'Emp2','656500','TECH2');

